# Generated by Django 3.2.4 on 2021-06-23 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=20)),
                ('order_type', models.CharField(max_length=20)),
                ('submitted_at', models.DateTimeField()),
                ('sku_name', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku_id', models.CharField(max_length=50)),
                ('sku_name', models.CharField(max_length=50)),
                ('product_name', models.CharField(max_length=50)),
                ('product_category', models.CharField(max_length=50)),
                ('product_description', models.CharField(max_length=255)),
                ('style', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('size', models.IntegerField()),
                ('available_to_sell', models.IntegerField()),
                ('sales_last_week', models.IntegerField()),
                ('sales_last_4_weeks', models.IntegerField()),
                ('sales_last_52_weeks', models.IntegerField()),
            ],
        ),
    ]
