# Generated by Django 3.2.4 on 2021-06-23 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sku',
            name='color',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='sku',
            name='sales_last_4_weeks',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sku',
            name='sales_last_52_weeks',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sku',
            name='sales_last_week',
            field=models.IntegerField(default=0),
        ),
    ]
