# Generated by Django 3.2.4 on 2021-06-23 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20210623_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sku',
            name='size',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
