# Generated by Django 3.2.4 on 2021-06-23 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_sku_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='sku',
            name='weeks_available',
            field=models.IntegerField(default=0),
        ),
    ]
