# Generated by Django 3.2.4 on 2021-06-23 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_auto_20210623_1620'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sku',
            name='weeks_available',
        ),
    ]
