# Generated by Django 3.2.4 on 2021-06-25 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_remove_sku_weeks_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='sku',
            name='inseam',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
