# Generated by Django 3.2.4 on 2021-07-05 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_auto_20210705_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='sku',
            name='current_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
