# Generated by Django 3.2.4 on 2021-07-06 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_sku_current_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='sku',
            name='future_status2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
