# Generated by Django 3.2.4 on 2021-08-03 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_sku_upc'),
    ]

    operations = [
        migrations.AddField(
            model_name='sku',
            name='average_week',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sku',
            name='weeks_available',
            field=models.IntegerField(default=0),
        ),
    ]
